export const mockData: any = {
  course: {
    name: 'Beispiel Kurs',
    maxParticipants: 10,
    isCancelled: false,
    location: {
      name: 'Halle',
      icon: 'https://picsum.photos/100',
    },
    trainer: {
      name: 'Willi',
      icon: 'https://api.lorem.space/image/face?w=100&h=100',
    },
    participants: [
      {
        firstName: 'Angela',
        lastName: 'Merkel',
        insurance: true,
        prevention: false,
        vaccinated: true,
        boostered: false,
        xcard: true,
        trial: false,
      },
      {
        firstName: 'Paul',
        lastName: 'Baumgarten',
        insurance: false,
        prevention: false,
        vaccinated: true,
        boostered: true,
        xcard: false,
        trial: false,
      },
      {
        firstName: 'Philip',
        lastName: 'Niemand',
        insurance: false,
        prevention: true,
        vaccinated: false,
        boostered: false,
        xcard: true,
        trial: false,
      },
    ],
    waitlist: [
      {
        firstName: 'Max',
        lastName: 'Mustermann',
        insurance: true,
        prevention: false,
        vaccinated: true,
        boostered: true,
        xcard: true,
        trial: false,
      },
      {
        firstName: 'Willi',
        lastName: 'Braun',
        insurance: true,
        prevention: false,
        vaccinated: true,
        boostered: true,
        xcard: true,
        trial: false,
      },
      {
        firstName: 'Herbert',
        lastName: 'Grönemeyer',
        insurance: true,
        prevention: false,
        vaccinated: true,
        boostered: true,
        xcard: true,
        trial: false,
      },
    ],
  },
};
